### ISSUE TITLE
Are the querstions same with the src dataset

### ISSUE THREAD

**Issue by Ezra-Yu** [psunlpgroup/VisOnlyQA#1]
I've noticed that many sources of your test dataset currently come from existing open-source datasets. I'm wondering if you used these questions with the original datasets being completely identical to the queries, or did you only use the images from them?

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/c1940758-a3d8-4109-89a1-0b030fcb1e75">

**Comment by ryokamoi** [comment]
We only use the images from them.
